services:
  backend:
    build: ./backend
    container_name: masjid-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./:/project
      - ./backend/uploads:/app/uploads
      - ./backend/data.db:/app/data.db
    restart: unless-stopped
